Fixes JENKINS-37184 and JENKINS-5124
jenkinsci/subversion-plugin pull request #165
Opened 2016-08-04 17:06 UTC by openbrian

Log the exception that is thrown if Jenksins can't get info() on a subversion repository using a tunnel.  When the repository factory creates the repository, set the tunnel provider based on default svn options.

2016-08-04 18:47 UTC, recena commented on src/main/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinition.java
> +      LOGGER.log(Level.SEVERE, "An SVN exception occurred", e);
The message does not provide any value

2016-08-04 18:47 UTC, recena commented on src/main/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinition.java
> +      repo.setTunnelProvider( SubversionSCM.createDefaultSVNOptions() );
Please, `repo.setTunnelProvider(SubversionSCM.createDefaultSVNOptions());`

2016-08-04 18:59 UTC, openbrian commented on src/main/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinition.java
> +      LOGGER.log(Level.SEVERE, "An SVN exception occurred", e);
It's doesn't?  It tells a sysadmin that they have a misconfigured repository line when they specify svn+foo://domain/path and foo is not a configured tunnel in .subversion/config.  It's much better then throwing that exception on the floor.  It's the only way I would know how to fix the bug.

2016-08-04 18:59 UTC, openbrian commented on src/main/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinition.java
> +      repo.setTunnelProvider( SubversionSCM.createDefaultSVNOptions() );
I'm on it.

2016-08-15 17:08 UTC, openbrian commented
I believe this patch is ready to be merged.  If not, please provide feedback.

2016-10-19 17:51 UTC, openbrian commented
Any updates on this PR?

2017-06-16 14:28 UTC, jglick requested changes
merge conflicts

2017-06-16 14:28 UTC, jglick commented on src/main/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinition.java
> +      repo.setTunnelProvider(SubversionSCM.createDefaultSVNOptions());
This is not about logging, is it?

2017-06-20 23:36 UTC, openbrian commented
Well it's been about a year, so I don't remember.  I'll review and update the ticket.

I can tell you, the efect of this omission is, under some conditions, the list of known braches and tags will not populate a drop down select box. I believe it was like Build Parameterized or some form like that.

The root cause of the issue was not being logged.  We didn't know what to fix. The feature was unusable.

I don't recall what the root cause was, but I feel it was related to the fact that we use ssh+svn and our ssh uses Kerberos for authentication.

2026-09-09 09:14 UTC, Eccenux commented
Merge conflict; possibly not a problem any more.

2026-09-09 09:14 UTC, closed without merging