Update UpdateUpdater.java (Fail build when locked file instead of fresh check out. This is helpful when repositories are very large and takes hours for fresh check out which flushes configurations as well.)
jenkinsci/subversion-plugin pull request #180
Opened 2017-03-20 12:35 UTC by clickjohndahl

Fail build when locked file instead of fresh check out. This is helpful when repositories are very large and takes hours for fresh check out which flushes configurations as well.

2017-06-16 14:22 UTC, jglick commented
Seems like this could break legitimate use cases? Unclear.

2017-06-16 14:39 UTC, oleg-nenashev requested changes
Yes, breaking change. Needs a configurable behavior at least

2019-12-30 09:31 UTC, ronaldoooo commented
@oleg-nenashev  @jglick I really need this feature to be in the release version. Everytime my workspace get locked by some circumstance, jenkins automaticlly clean my workspace without any suggestions. My whole workspace get lost (Bigger than 200GB) and need a fresh checkout. That kills me.

2019-12-30 09:37 UTC, oleg-nenashev commented
@ronaldoooo Hi. Would you be interested to submit a pull request which addresses the review comments? I might be able to merge and release it then

2026-09-09 09:48 UTC, Eccenux commented
Stale; possibly not a problem any more.

2026-09-09 09:48 UTC, closed without merging