JENKINS-25825 Subversion plugin refuses to checkout branch at specifi…
jenkinsci/subversion-plugin pull request #185
Opened 2017-05-29 08:14 UTC by i386

…c revision when it no longer exists in HEAD

2017-05-29 08:19 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-05-29 11:04 UTC, stephenc approved these changes
Seems ok

2017-05-30 14:57 UTC, jglick reviewed
This sounds like something which could, and should, be covered by a new test case.

2017-05-31 04:11 UTC, i386 commented
FYI this isn't mergable. Another problem reported on the ticket.

2017-06-08 10:13 UTC, oleg-nenashev requested changes
NO-MERGE according to the comment from @i386

2026-05-07 19:03 UTC, closed without merging