added support for AdditionalCredentials to SubversionSCMSource and fixed issues with externals
jenkinsci/subversion-plugin pull request #189
Opened 2017-06-20 14:11 UTC by r-funke

This fixes issues with multibranch pipeline jobs and SVN externals. The main problem was that SubversionSCMSource did not allow to configure additional credentials, which caused "svn: E200015: ISVNAuthentication" errors. This patch fixes that. The second problem was that during "Scan Multibranch Pipeline" it was just checked whether the revision number of the SVN root directory changed. Thus it did not detect changes in externals. That was fixed by declaring revision number non-deterministic in SCMRevisionImpl, if additional credentials are configured. Then, Jenkins polls for changes in the whole repository.

This should fix JENKINS-35227 and JENKINS-32167. I am not able to post a comment in the bug reports, because I failed to create an account on jenkins.io.

2017-06-21 18:41 UTC, jglick submitted a review, later dismissed

2017-06-21 18:41 UTC, jglick commented on src/main/java/hudson/scm/SubversionSCM.java
> -    public static class AdditionalCredentials extends AbstractDescribableImpl<AdditionalCredentials> {
No, you must leave this class where it was for reasons of settings compatibility. Nothing is stopping `SubversionSCMSource` from reusing it here.

2017-06-21 18:41 UTC, jglick commented on src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
> +    public SubversionSCMSource(String id, String remoteBase, List<AdditionalCredentials> additionalCredentials) {
No, this should be in a `@DataBoundSetter` only.

2017-06-21 18:41 UTC, jglick commented on src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
> +                return false;
Nondeterministic revisions are acceptable only for SCMs which inherently cannot support determinism, like CVS I suppose (though even there `-D` timestamps may offer a solution). In the case of Subversion with externals, we would rather need to extend `SCMRevisionImpl` to encode the revision number in each external encountered.

2017-06-21 18:41 UTC, jglick commented on src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
> +            return new SCMRevisionImpl(head, svnEntry.getRevision(), (additionalCredentials.size()>0));
This is not precise. Additional credentials might have been specified but not actually used. More plausibly, the server may use externals which simply do not need any distinct credentials.

2017-06-22 11:01 UTC, r-funke commented
@jglick thank you for your input. I've moved AdditionalCredentials back in place.

Regarding the non-deterministic revision, it was an easy solution (or workaround) for Jenkins not detecting changes in externals. Of course, the clean solution would be to extend SCMRevisionImpl. But to me it seems that it requires quite a lot of effort to get that done. 

Would it be okay to have a checkbox in the config and let the user specify whether isDeterministic() should return true or false?

2017-06-23 06:26 UTC, oleg-nenashev requested changes
This PR introduces a breaking change + additionalCredentials handling seems to be error-prone and redundant in some cases.

I would also expect to see a test suite for the change

2017-06-23 06:26 UTC, oleg-nenashev commented on src/main/java/hudson/scm/SubversionSCM.java
> +        this(locations, useUpdate, false, browser, excludedRegions, excludedUsers, excludedRevprop, excludedCommitMessages);
May cause merge conflicts without a reason

2017-06-23 06:26 UTC, oleg-nenashev commented on src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
> +    private List<AdditionalCredentials> additionalCredentials;
from what I see it still may be null when you read data from the disk

2017-06-23 06:26 UTC, oleg-nenashev commented on src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
> +        return(additionalCredentials);
FindBugs will grumble about exposing external implementation. Either make it `@Restricted` for Jelly only or wrap with `unmodifyableList`

2017-06-23 06:26 UTC, oleg-nenashev commented on src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
> +        public SCMRevisionImpl(SCMHead head, long revision, boolean usesExternals) {
Breaking change, the class was public

2017-06-23 06:26 UTC, oleg-nenashev commented on src/main/java/hudson/scm/SubversionSCM.java
> +    public SubversionSCM(String[] svnUrls, String[] credentialIds, String[] locals, List<AdditionalCredentials> additionalCredentials) {
I do not believe new methods are really required if you implement proper null handling in the original constructors. You say these methods are useful for testing, but there is no autotests

2017-06-23 06:26 UTC, oleg-nenashev commented on src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
> +        this.additionalCredentials =  new ArrayList<AdditionalCredentials>();
Usage of this collection is ineffective if you do not plan to modify it on the flight. Use `Collections.emptyList()` instead in the code

2017-06-23 15:33 UTC, r-funke commented on src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
> +        return(additionalCredentials);
Thank you for your comments. How do I make it restricted? Does adding "@Restricted(NoExternalUse.class)" work?

2017-06-27 13:23 UTC, r-funke commented
Would it help to remove the changes to SCMRevisionImpl and isDeterministic() from this PR to get it accepted? Then this PR would only cover AdditionalCredentials for SubversionSCMSource, i.e. for multibranch pipeline jobs, which would solve JENKINS-35227.

2017-07-04 10:17 UTC, oleg-nenashev commented on src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
> +        return(additionalCredentials);
yes

2017-07-04 10:19 UTC, oleg-nenashev commented
> So maybe I should create an issue for that first.

+1. An issue would be useful. The scope of this change is not that big, so probably we could have two fixes in a single PR

2017-07-04 10:20 UTC, oleg-nenashev commented
Separate pull requests would be better though

2017-07-07 13:12 UTC, r-funke commented
Okay, this PR is now only about additional credentials. Is it good enough to be accepted?

2017-07-07 14:35 UTC, oleg-nenashev commented on src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
> +        return(additionalCredentials);
would be better to just `return Collections.unmodifyableList(additionalCredentials)`

2017-07-07 14:36 UTC, oleg-nenashev commented
Yes, it looks much better now. I probably could live even without tests for it. @jglick WDYT?

2017-07-24 10:42 UTC, r-funke commented
Any news on this issue?

2017-09-04 10:01 UTC, DavidA2014 commented
Any news on this issue?  This fix would help me.

2017-09-13 16:16 UTC, jglick commented
Still would benefit from tests. Probably ought to be migrated to traits in a newer `scm-api`. Requires a maintainer to do this work I think.

2018-03-04 20:36 UTC, imakowski commented
When this will be released?

2023-07-24 16:26 UTC, larsbier commented
I try to understand, what's happened and why :-) I have a provider, which needs username/password and PIN-protected client certificate. And I have to move my multibranch pipeline to this svn provider.
So I cannot say, that this request is obsolete :-)

2026-09-09 09:47 UTC, Eccenux commented
Stale; possibly not a problem any more.

2026-09-09 09:47 UTC, closed without merging