Update README.md [JENKINS-65132] Fix example script for notifyCommit
jenkinsci/subversion-plugin pull request #253
Opened 2021-03-19 06:52 UTC by mhuijgen

The crumb needs to be appended to the headers, not replacing the Content-Type header.
Required for the notification to work on Jenkins LTS 2.277.1 and newer (will throw 500 server error otherwise).

https://issues.jenkins.io/browse/JENKINS-65132

- [X ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [X ] Ensure that the pull request title represents the desired changelog entry
- [X ] Please describe what you did
- [X ] Link to relevant issues in GitHub or Jira
- [X ] Link to relevant pull requests, esp. upstream and downstream changes
- [X ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-03-19 14:23 UTC, jglick approved these changes

2021-03-19 14:23 UTC, jglick commented on README.md
>          # so we can present a valid crumb or a proper header
This comment is now misleading I think?

2021-03-19 14:23 UTC, jglick commented on README.md
> +            $CRUMB
Confusing to use one variable for two purposes: first an actual crumb, then a `wget` arg. Maybe clearer to use a separate var like `CRUMB_HEADER` (and rename `HEADER` to `CONTENT_TYPE_HEADER`), or something like this.

2021-10-03 12:12 UTC, didiez requested changes
+1 to rename variables to make things more clear

2021-10-03 12:12 UTC, didiez commented on README.md
> +        if [ "$CRUMB" != "" ]; then CRUMB="--header $CRUMB"; fi
```suggestion
        if [ "$CRUMB" != "" ]; then CRUMB_HEADER="--header $CRUMB"; fi
```

2021-10-03 12:12 UTC, didiez commented on README.md
> +            $CRUMB
```suggestion
            $CONTENT_TYPE_HEADER \
            $CRUMB_HEADER \
```

2021-10-03 12:51 UTC, didiez approved these changes

2021-10-03 12:53 UTC, merged